using AngleSharp.Html.Parser;
using Kontent.Ai.Delivery.Caching;
using Kontent.Ai.Delivery.ContentItems;
using Kontent.Ai.Delivery.ContentItems.Processing;
using Kontent.Ai.Delivery.Handlers;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http.Resilience;
using Microsoft.Extensions.Options;
using Polly;

namespace Kontent.Ai.Delivery.Configuration;

/// <summary>
/// A builder for creating <see cref="IDeliveryClient"/> instances without dependency injection.
/// </summary>
/// <remarks>
/// <para>
/// This builder provides a fluent API for configuring and instantiating <see cref="IDeliveryClient"/>
/// outside of a DI container. Internally, it uses a private <see cref="IServiceCollection"/>
/// to resolve all dependencies, ensuring the same functionality as DI-registered clients.
/// </para>
/// <para>
/// <b>Lifecycle:</b> The returned <see cref="IDeliveryClient"/> is thread-safe and should be used
/// as a singleton for the lifetime of your application. Each <see cref="Build"/> call creates
/// a new independent client with its own HTTP client and cache (if configured). Do not create
/// multiple client instances unless you specifically need isolated configurations.
/// </para>
/// <para>
/// Example usage:
/// <code>
/// // Simple usage with environment ID
/// var client = DeliveryClientBuilder
///     .WithEnvironmentId("your-environment-id")
///     .Build();
///
/// // With preview API and type provider
/// var client = DeliveryClientBuilder
///     .WithOptions(opts => opts
///         .WithEnvironmentId("your-environment-id")
///         .UsePreviewApi("preview-api-key")
///         .Build())
///     .WithTypeProvider(new GeneratedTypeProvider())
///     .WithMemoryCache(TimeSpan.FromMinutes(30))
///     .Build();
/// </code>
/// </para>
/// </remarks>
public sealed class DeliveryClientBuilder
{
    private DeliveryOptions? _deliveryOptions;
    private ITypeProvider? _typeProvider;
    private IDistributedCache? _distributedCache;
    private TimeSpan? _cacheExpiration;
    private CacheType _cacheType = CacheType.None;

    private enum CacheType
    {
        None,
        Memory,
        Distributed
    }

    private DeliveryClientBuilder() { }

    /// <summary>
    /// Creates a builder configured with the specified environment identifier for Production API.
    /// </summary>
    /// <param name="environmentId">The identifier of a Kontent.ai environment.</param>
    /// <returns>A builder for optional client configuration.</returns>
    public static DeliveryClientBuilder WithEnvironmentId(string environmentId)
    {
        var builder = new DeliveryClientBuilder
        {
            _deliveryOptions = DeliveryOptionsBuilder.CreateInstance()
                .WithEnvironmentId(environmentId)
                .UseProductionApi()
                .Build()
        };
        return builder;
    }

    /// <summary>
    /// Creates a builder configured with the specified environment identifier for Production API.
    /// </summary>
    /// <param name="environmentId">The identifier of a Kontent.ai environment.</param>
    /// <returns>A builder for optional client configuration.</returns>
    public static DeliveryClientBuilder WithEnvironmentId(Guid environmentId)
    {
        var builder = new DeliveryClientBuilder
        {
            _deliveryOptions = DeliveryOptionsBuilder.CreateInstance()
                .WithEnvironmentId(environmentId)
                .UseProductionApi()
                .Build()
        };
        return builder;
    }

    /// <summary>
    /// Creates a builder with additional configuration via the options builder.
    /// </summary>
    /// <param name="buildDeliveryOptions">A delegate that creates an instance of the <see cref="DeliveryOptions"/> using the specified <see cref="IDeliveryOptionsBuilder"/>.</param>
    /// <returns>A builder for optional client configuration.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="buildDeliveryOptions"/> is null.</exception>
    public static DeliveryClientBuilder WithOptions(Func<IDeliveryOptionsBuilder, DeliveryOptions> buildDeliveryOptions)
    {
        ArgumentNullException.ThrowIfNull(buildDeliveryOptions);

        var builder = new DeliveryClientBuilder
        {
            _deliveryOptions = buildDeliveryOptions(DeliveryOptionsBuilder.CreateInstance())
        };
        return builder;
    }

    /// <summary>
    /// Sets a custom type provider for mapping content type codenames to CLR types.
    /// </summary>
    /// <param name="typeProvider">
    /// The type provider instance. Typically generated by the Kontent.ai model generator.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="typeProvider"/> is null.</exception>
    /// <remarks>
    /// If not set, a default type provider is used that returns null for all mappings,
    /// resulting in dynamic model resolution.
    /// </remarks>
    public DeliveryClientBuilder WithTypeProvider(ITypeProvider typeProvider)
    {
        ArgumentNullException.ThrowIfNull(typeProvider);
        _typeProvider = typeProvider;
        return this;
    }

    /// <summary>
    /// Enables in-memory caching for API responses.
    /// </summary>
    /// <param name="defaultExpiration">
    /// Default cache entry expiration time. If null, defaults to 1 hour.
    /// Individual queries can override this using query parameters.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <remarks>
    /// <para>
    /// The builder creates and manages an <see cref="IMemoryCache"/> instance internally.
    /// For scenarios requiring shared cache instances across multiple clients, use DI registration instead.
    /// </para>
    /// <para>
    /// Cannot be combined with <see cref="WithDistributedCache"/>. Calling both will use the last one configured.
    /// </para>
    /// </remarks>
    public DeliveryClientBuilder WithMemoryCache(TimeSpan? defaultExpiration = null)
    {
        _cacheType = CacheType.Memory;
        _cacheExpiration = defaultExpiration;
        _distributedCache = null;
        return this;
    }

    /// <summary>
    /// Enables distributed caching for API responses using a provided <see cref="IDistributedCache"/> instance.
    /// </summary>
    /// <param name="distributedCache">
    /// The distributed cache instance (e.g., Redis, SQL Server, NCache).
    /// </param>
    /// <param name="defaultExpiration">
    /// Default cache entry expiration time. If null, defaults to 1 hour.
    /// Individual queries can override this using query parameters.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="distributedCache"/> is null.</exception>
    /// <remarks>
    /// <para>
    /// Unlike <see cref="WithMemoryCache"/>, this method requires you to provide the distributed cache instance.
    /// This is because distributed cache implementations (Redis, SQL Server, etc.) require external configuration.
    /// </para>
    /// <para>
    /// Cannot be combined with <see cref="WithMemoryCache"/>. Calling both will use the last one configured.
    /// </para>
    /// </remarks>
    public DeliveryClientBuilder WithDistributedCache(IDistributedCache distributedCache, TimeSpan? defaultExpiration = null)
    {
        ArgumentNullException.ThrowIfNull(distributedCache);

        _cacheType = CacheType.Distributed;
        _cacheExpiration = defaultExpiration;
        _distributedCache = distributedCache;
        return this;
    }

    /// <summary>
    /// Builds and returns a configured <see cref="IDeliveryClient"/> instance.
    /// </summary>
    /// <returns>A fully configured <see cref="IDeliveryClient"/> instance.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when validation fails (e.g., missing environment ID or API key).
    /// </exception>
    /// <remarks>
    /// <para>
    /// This method validates the configuration and builds all required dependencies.
    /// The returned client is thread-safe and can be reused for the lifetime of the application.
    /// </para>
    /// <para>
    /// The builder can be used to create multiple client instances, but each call to <see cref="Build"/>
    /// creates a new independent client with its own HTTP client and cache (if configured).
    /// </para>
    /// </remarks>
    public IDeliveryClient Build()
    {
        if (_deliveryOptions is null)
        {
            throw new InvalidOperationException(
                "DeliveryOptions must be configured. Call WithEnvironmentId() or WithOptions() before Build().");
        }

        // Validate options using DataAnnotations
        ValidateOptions(_deliveryOptions);

        // Build the service provider with all required dependencies
        var services = new ServiceCollection();

        ConfigureServices(services);

        var serviceProvider = services.BuildServiceProvider();

        return serviceProvider.GetRequiredService<IDeliveryClient>();
    }

    private void ConfigureServices(IServiceCollection services)
    {
        // Register options
        var deliveryOptions = _deliveryOptions!;
        services.Configure<DeliveryOptions>(opt => ConfigureOptions(opt, deliveryOptions));
        services.AddOptions<DeliveryOptions>()
            .ValidateDataAnnotations()
            .ValidateOnStart();

        // Register JSON serialization options (shared across SDK)
        services.AddSingleton(RefitSettingsProvider.CreateDefaultJsonSerializerOptions());

        // Register core services
        services.AddSingleton<IPropertyMapper, PropertyMapper>();
        services.AddSingleton<IContentDeserializer, ContentDeserializer>();
        services.AddSingleton<IHtmlParser, HtmlParser>();

        // Register ITypeProvider (custom or default)
        if (_typeProvider is not null)
        {
            services.AddSingleton(_typeProvider);
        }
        else
        {
            services.AddSingleton<ITypeProvider, TypeProvider>();
        }

        // Register typing strategy
        services.AddSingleton<IItemTypingStrategy, DefaultItemTypingStrategy>();

        // Register caching services based on configuration
        ConfigureCaching(services);

        // Register elements post-processor
        services.AddSingleton<IElementsPostProcessor, ElementsPostProcessor>();

        // Register HTTP handlers
        services.AddTransient<TrackingHandler>();
        services.AddTransient<DeliveryAuthenticationHandler>();

        // Register and configure HTTP client with Refit
        var refitSettings = RefitSettingsProvider.CreateDefaultSettings();

        var httpClientBuilder = services
            .AddRefitClient<IDeliveryApi>(refitSettings)
            .ConfigureHttpClient((sp, httpClient) =>
            {
                var optionsMonitor = sp.GetRequiredService<IOptionsMonitor<DeliveryOptions>>();
                httpClient.BaseAddress = new Uri(optionsMonitor.CurrentValue.GetBaseUrl(), UriKind.Absolute);
            });

        // Configure resilience
        if (_deliveryOptions!.EnableResilience)
        {
            httpClientBuilder.AddResilienceHandler("delivery", ConfigureDefaultResilience);
        }

        // Add message handlers
        httpClientBuilder.AddHttpMessageHandler<TrackingHandler>();
        httpClientBuilder.AddHttpMessageHandler<DeliveryAuthenticationHandler>();

        // Register the DeliveryClient
        services.AddSingleton<IDeliveryClient>(sp =>
        {
            var deliveryApi = sp.GetRequiredService<IDeliveryApi>();
            var optionsMonitor = sp.GetRequiredService<IOptionsMonitor<DeliveryOptions>>();
            var elementsPostProcessor = sp.GetRequiredService<IElementsPostProcessor>();
            var cacheManager = sp.GetService<IDeliveryCacheManager>();

            return new DeliveryClient(
                deliveryApi,
                optionsMonitor,
                elementsPostProcessor,
                cacheManager);
        });
    }

    private void ConfigureCaching(IServiceCollection services)
    {
        switch (_cacheType)
        {
            case CacheType.Memory:
                // Create and register IMemoryCache
                services.AddMemoryCache();
                services.AddSingleton<IDeliveryCacheManager>(sp =>
                    new MemoryCacheManager(
                        sp.GetRequiredService<IMemoryCache>(),
                        keyPrefix: null,
                        _cacheExpiration));
                services.AddSingleton<IContentDependencyExtractor, ContentDependencyExtractor>();
                break;

            case CacheType.Distributed:
                // Register the provided distributed cache
                services.AddSingleton(_distributedCache!);
                services.AddSingleton<IDeliveryCacheManager>(sp =>
                    new DistributedCacheManager(
                        sp.GetRequiredService<IDistributedCache>(),
                        keyPrefix: null,
                        _cacheExpiration));
                services.AddSingleton<IContentDependencyExtractor, ContentDependencyExtractor>();
                break;

            case CacheType.None:
            default:
                // No caching - use null extractor
                services.AddSingleton<IContentDependencyExtractor>(NullContentDependencyExtractor.Instance);
                break;
        }
    }

    private static void ConfigureDefaultResilience(ResiliencePipelineBuilder<HttpResponseMessage> builder)
    {
        // Retry policy
        builder.AddRetry(new HttpRetryStrategyOptions
        {
            MaxRetryAttempts = 3,
            Delay = TimeSpan.FromSeconds(1),
            BackoffType = DelayBackoffType.Exponential,
            UseJitter = true,
            ShouldHandle = args => ValueTask.FromResult(
                args.Outcome.Result?.IsSuccessStatusCode == false &&
                IsRetryableStatusCode(args.Outcome.Result?.StatusCode))
        });

        // Timeout policy
        builder.AddTimeout(TimeSpan.FromSeconds(30));
    }

    private static bool IsRetryableStatusCode(System.Net.HttpStatusCode? statusCode)
        => statusCode is
            System.Net.HttpStatusCode.TooManyRequests or
            System.Net.HttpStatusCode.RequestTimeout or
            System.Net.HttpStatusCode.InternalServerError or
            System.Net.HttpStatusCode.BadGateway or
            System.Net.HttpStatusCode.ServiceUnavailable or
            System.Net.HttpStatusCode.GatewayTimeout;

    private static void ConfigureOptions(DeliveryOptions target, DeliveryOptions source)
    {
        target.EnvironmentId = source.EnvironmentId;
        target.EnableResilience = source.EnableResilience;
        target.ProductionEndpoint = source.ProductionEndpoint;
        target.PreviewEndpoint = source.PreviewEndpoint;
        target.PreviewApiKey = source.PreviewApiKey;
        target.UsePreviewApi = source.UsePreviewApi;
        target.UseSecureAccess = source.UseSecureAccess;
        target.SecureAccessApiKey = source.SecureAccessApiKey;
        target.IncludeTotalCount = source.IncludeTotalCount;
        target.WaitForLoadingNewContent = source.WaitForLoadingNewContent;
        target.DefaultRenditionPreset = source.DefaultRenditionPreset;
    }

    private static void ValidateOptions(DeliveryOptions options)
    {
        var validationContext = new System.ComponentModel.DataAnnotations.ValidationContext(options);
        var validationResults = new List<System.ComponentModel.DataAnnotations.ValidationResult>();

        if (!System.ComponentModel.DataAnnotations.Validator.TryValidateObject(
            options, validationContext, validationResults, validateAllProperties: true))
        {
            var errors = string.Join("; ", validationResults.Select(r => r.ErrorMessage));
            throw new InvalidOperationException($"Invalid DeliveryOptions: {errors}");
        }
    }
}
