using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Kontent.Ai.Delivery.Configuration;

/// <summary>
/// A builder for creating <see cref="IDeliveryClient"/> instances without dependency injection.
/// </summary>
/// <remarks>
/// <para>
/// This builder provides a fluent API for configuring and instantiating <see cref="IDeliveryClient"/>
/// outside of a DI container. Internally, it uses a private <see cref="IServiceCollection"/>
/// to resolve all dependencies, ensuring the same functionality as DI-registered clients.
/// </para>
/// <para>
/// <b>Lifecycle:</b> The returned <see cref="IDeliveryClient"/> is thread-safe and should be used
/// as a singleton for the lifetime of your application. Each <see cref="Build"/> call creates
/// a new independent client with its own HTTP client and cache (if configured). Do not create
/// multiple client instances unless you specifically need isolated configurations.
/// </para>
/// <para>
/// Example usage:
/// <code>
/// // Simple usage with Production API
/// using var container = DeliveryClientBuilder
///     .WithOptions(opts => opts
///         .WithEnvironmentId("your-environment-id")
///         .UseProductionApi()
///         .Build())
///     .Build();
///
/// // With Preview API and type provider
/// using var container2 = DeliveryClientBuilder
///     .WithOptions(opts => opts
///         .WithEnvironmentId("your-environment-id")
///         .UsePreviewApi("preview-api-key")
///         .Build())
///     .WithTypeProvider(new GeneratedTypeProvider())
///     .WithMemoryCache(TimeSpan.FromMinutes(30))
///     .Build();
/// </code>
/// </para>
/// </remarks>
public sealed class DeliveryClientBuilder
{
    private DeliveryOptions? _deliveryOptions;
    private ITypeProvider? _typeProvider;
    private Action<IServiceCollection>? _configureCache;
    private ILoggerFactory? _loggerFactory;

    private DeliveryClientBuilder() { }

    /// <summary>
    /// Creates a builder with configuration via the options builder.
    /// </summary>
    /// <param name="buildDeliveryOptions">A delegate that creates an instance of the <see cref="DeliveryOptions"/> using the specified <see cref="IDeliveryOptionsBuilder"/>.</param>
    /// <returns>A builder for optional client configuration.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="buildDeliveryOptions"/> is null.</exception>
    public static DeliveryClientBuilder WithOptions(Func<IDeliveryOptionsBuilder, DeliveryOptions> buildDeliveryOptions)
    {
        ArgumentNullException.ThrowIfNull(buildDeliveryOptions);

        var builder = new DeliveryClientBuilder
        {
            _deliveryOptions = buildDeliveryOptions(DeliveryOptionsBuilder.CreateInstance())
        };
        return builder;
    }

    /// <summary>
    /// Sets a custom type provider for mapping content type codenames to CLR types.
    /// </summary>
    /// <param name="typeProvider">
    /// The type provider instance. Typically generated by the Kontent.ai model generator.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="typeProvider"/> is null.</exception>
    /// <remarks>
    /// If not set, a default type provider is used that returns null for all mappings,
    /// resulting in dynamic model resolution.
    /// </remarks>
    public DeliveryClientBuilder WithTypeProvider(ITypeProvider typeProvider)
    {
        ArgumentNullException.ThrowIfNull(typeProvider);
        _typeProvider = typeProvider;
        return this;
    }

    /// <summary>
    /// Enables in-memory caching for API responses.
    /// </summary>
    /// <param name="defaultExpiration">
    /// Default cache entry expiration time. If null, defaults to 1 hour.
    /// Individual queries can override this using query parameters.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <remarks>
    /// <para>
    /// The builder creates and manages an <see cref="Microsoft.Extensions.Caching.Memory.IMemoryCache"/> instance internally.
    /// For scenarios requiring shared cache instances across multiple clients, use DI registration instead.
    /// </para>
    /// <para>
    /// Cannot be combined with <see cref="WithDistributedCache"/>. Calling both will use the last one configured.
    /// </para>
    /// </remarks>
    public DeliveryClientBuilder WithMemoryCache(TimeSpan? defaultExpiration = null)
    {
        _configureCache = services => services.AddDeliveryMemoryCache(
            clientName: DeliveryClientNames.Default,
            keyPrefix: string.Empty,
            defaultExpiration: defaultExpiration);
        return this;
    }

    /// <summary>
    /// Enables distributed caching for API responses using a provided <see cref="IDistributedCache"/> instance.
    /// </summary>
    /// <param name="distributedCache">
    /// The distributed cache instance (e.g., Redis, SQL Server, NCache).
    /// </param>
    /// <param name="defaultExpiration">
    /// Default cache entry expiration time. If null, defaults to 1 hour.
    /// Individual queries can override this using query parameters.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="distributedCache"/> is null.</exception>
    /// <remarks>
    /// <para>
    /// Unlike <see cref="WithMemoryCache"/>, this method requires you to provide the distributed cache instance.
    /// This is because distributed cache implementations (Redis, SQL Server, etc.) require external configuration.
    /// </para>
    /// <para>
    /// Cannot be combined with <see cref="WithMemoryCache"/>. Calling both will use the last one configured.
    /// </para>
    /// </remarks>
    public DeliveryClientBuilder WithDistributedCache(IDistributedCache distributedCache, TimeSpan? defaultExpiration = null)
    {
        ArgumentNullException.ThrowIfNull(distributedCache);

        _configureCache = services =>
        {
            services.AddSingleton(distributedCache);
            services.AddDeliveryDistributedCache(
                clientName: DeliveryClientNames.Default,
                keyPrefix: string.Empty,
                defaultExpiration: defaultExpiration);
        };
        return this;
    }

    /// <summary>
    /// Sets a custom logger factory for diagnostic logging.
    /// </summary>
    /// <param name="loggerFactory">
    /// The logger factory instance. Use your preferred logging framework (Serilog, NLog, etc.)
    /// or Microsoft.Extensions.Logging directly.
    /// </param>
    /// <returns>The builder instance for method chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="loggerFactory"/> is null.</exception>
    /// <remarks>
    /// <para>
    /// If not set, logging is disabled (no logging services are registered).
    /// </para>
    /// <para>
    /// Example usage:
    /// <code>
    /// var loggerFactory = LoggerFactory.Create(builder =>
    /// {
    ///     builder.AddConsole();
    ///     builder.SetMinimumLevel(LogLevel.Debug);
    /// });
    ///
    /// using var container = DeliveryClientBuilder
    ///     .WithOptions(opts => opts
    ///         .WithEnvironmentId("your-environment-id")
    ///         .UseProductionApi()
    ///         .Build())
    ///     .WithLoggerFactory(loggerFactory)
    ///     .Build();
    /// </code>
    /// </para>
    /// </remarks>
    public DeliveryClientBuilder WithLoggerFactory(ILoggerFactory loggerFactory)
    {
        ArgumentNullException.ThrowIfNull(loggerFactory);
        _loggerFactory = loggerFactory;
        return this;
    }

    /// <summary>
    /// Builds and returns a configured <see cref="IDeliveryClient"/> instance.
    /// </summary>
    /// <returns>A fully configured <see cref="IDeliveryClient"/> instance.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when validation fails (e.g., missing environment ID or API key).
    /// </exception>
    /// <remarks>
    /// <para>
    /// This method validates the configuration and builds all required dependencies.
    /// The returned container owns the client and its dependencies - dispose it when done.
    /// </para>
    /// <para>
    /// The builder can be used to create multiple client instances, but each call to <see cref="Build"/>
    /// creates a new independent client with its own HTTP client and cache (if configured).
    /// </para>
    /// <example>
    /// <code>
    /// using var container = DeliveryClientBuilder
    ///     .WithOptions(opts => opts
    ///         .WithEnvironmentId("your-env-id")
    ///         .UseProductionApi()
    ///         .Build())
    ///     .Build();
    ///
    /// var client = container.Client;
    /// var result = await client.Items&lt;Article&gt;().ExecuteAsync();
    /// </code>
    /// </example>
    /// </remarks>
    public IDeliveryClientContainer Build()
    {
        if (_deliveryOptions is null)
        {
            throw new InvalidOperationException(
                "DeliveryOptions must be configured. Call WithOptions() before Build().");
        }

        var services = new ServiceCollection();
        ConfigureServices(services);

        // Validate options and build dependencies (options validation happens during provider build due to ValidateOnStart)
        var serviceProvider = services.BuildServiceProvider(
            new ServiceProviderOptions { ValidateOnBuild = true, ValidateScopes = true });

        var client = serviceProvider.GetRequiredService<IDeliveryClient>();

        // Return a container that owns the service provider lifetime
        return new DeliveryClientContainer(serviceProvider, client);
    }

    private void ConfigureServices(IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        if (_loggerFactory is not null)
        {
            services.AddSingleton(_loggerFactory);
            services.AddSingleton(typeof(ILogger<>), typeof(Logger<>));
        }

        if (_typeProvider is not null)
        {
            services.AddSingleton(_typeProvider);
        }

        services.AddDeliveryClient(_deliveryOptions!);
        _configureCache?.Invoke(services);
    }
}
