// This code was generated by a kontent-generators-net tool 
// (see https://github.com/kontent-ai/model-generator-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Kontent.Ai.Delivery.Rx.Tests.Models.ContentTypes
{
    public class HostedVideo
    {
        public const string Codename = "hosted_video";
        public const string VideoIdCodename = "video_id";
        public const string VideoHostCodename = "video_host";

        public string VideoId { get; set; }
        public IEnumerable<IMultipleChoiceOption> VideoHost { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}