using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Kontent.Ai.Delivery.SourceGeneration;

/// <summary>
/// Incremental source generator that creates a compile-time type registry
/// from classes decorated with [ContentTypeCodename].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ContentTypeGenerator : IIncrementalGenerator
{
    private const string ContentTypeCodenameAttributeFullName = "Kontent.Ai.Delivery.Attributes.ContentTypeCodenameAttribute";
    private const string ContentTypeCodenameAttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Kontent.Ai.Delivery.Attributes;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
        public sealed class ContentTypeCodenameAttribute : global::System.Attribute
        {
            public ContentTypeCodenameAttribute(string codename)
            {
                Codename = codename;
            }

            public string Codename { get; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the marker attribute into the consuming compilation so users do not
        // need a separate Attributes package/reference.
        context.RegisterPostInitializationOutput(static pic =>
        {
            pic.AddSource("ContentTypeCodenameAttribute.g.cs", SourceText.From(ContentTypeCodenameAttributeSource, Encoding.UTF8));
        });

        // Stage 1: Collect only symbols decorated with [ContentTypeCodename]
        // via metadata lookup (avoids scanning unrelated symbols).
        var typeDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: ContentTypeCodenameAttributeFullName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, ct) => GetContentTypeInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // Stage 2: Collect all content type infos and generate
        var collected = typeDeclarations.Collect();

        context.RegisterSourceOutput(collected, static (spc, infos) => Execute(spc, infos));
    }

    private static ContentTypeInfo? GetContentTypeInfo(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // context.Attributes is already filtered to ContentTypeCodenameAttribute
        // by ForAttributeWithMetadataName — take the first (AllowMultiple = false).
        var attributeData = context.Attributes[0];

        string? codename = null;
        if (attributeData.ConstructorArguments.Length > 0)
        {
            var arg = attributeData.ConstructorArguments[0];
            codename = arg.Value as string;
        }

        // Get location for diagnostics
        var location = attributeData.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation()
            ?? context.TargetNode.GetLocation();

        return new ContentTypeInfo(
            codename: codename,
            fullyQualifiedTypeName: typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeName: typeSymbol.Name,
            location: location,
            isInterface: typeSymbol.TypeKind == TypeKind.Interface,
            isAbstract: typeSymbol.IsAbstract && typeSymbol.TypeKind == TypeKind.Class);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ContentTypeInfo> infos)
    {
        // Group by codename to detect duplicates
        var validInfos = new List<ContentTypeInfo>();
        var codenameToTypes = new Dictionary<string, List<ContentTypeInfo>>(StringComparer.OrdinalIgnoreCase);

        foreach (var info in infos)
        {
            // Check for invalid codename
            if (string.IsNullOrWhiteSpace(info.Codename))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidCodename,
                    info.Location));
                continue;
            }

            // Check for unsupported target types
            if (info.IsInterface || info.IsAbstract)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnsupportedTargetType,
                    info.Location,
                    info.TypeName));
                continue;
            }

            // Track for duplicate detection
            if (!codenameToTypes.TryGetValue(info.Codename!, out var typeList))
            {
                typeList = [];
                codenameToTypes[info.Codename!] = typeList;
            }
            typeList.Add(info);
            validInfos.Add(info);
        }

        // Report duplicate codenames
        var duplicateCodenames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var kvp in codenameToTypes)
        {
            if (kvp.Value.Count > 1)
            {
                duplicateCodenames.Add(kvp.Key);
                var typeNames = string.Join(", ", kvp.Value.Select(i => i.TypeName));
                foreach (var info in kvp.Value)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.DuplicateCodename,
                        info.Location,
                        kvp.Key,
                        typeNames));
                }
            }
        }

        // Filter out types with duplicate codenames from generation
        var finalInfos = validInfos
            .Where(i => !duplicateCodenames.Contains(i.Codename!))
            .OrderBy(i => i.Codename, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Always generate the type provider (even if empty)
        var source = GenerateTypeProvider(finalInfos);
        context.AddSource("GeneratedTypeProvider.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateTypeProvider(List<ContentTypeInfo> infos)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Kontent.Ai.Delivery.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace Kontent.Ai.Delivery.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated type provider mapping content type codenames to CLR types.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class GeneratedTypeProvider : ITypeProvider");
        sb.AppendLine("{");

        // Codename to Type dictionary
        sb.AppendLine("    private static readonly Dictionary<string, Type> _codenameToType =");
        sb.AppendLine("        new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var info in infos)
        {
            sb.AppendLine($"        {{ \"{EscapeString(info.Codename!)}\", typeof({info.FullyQualifiedTypeName}) }},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // Type to Codename dictionary
        sb.AppendLine("    private static readonly Dictionary<Type, string> _typeToCodename = new()");
        sb.AppendLine("    {");
        foreach (var info in infos)
        {
            sb.AppendLine($"        {{ typeof({info.FullyQualifiedTypeName}), \"{EscapeString(info.Codename!)}\" }},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // GetType method
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public Type? GetType(string contentType)");
        sb.AppendLine("        => _codenameToType.TryGetValue(contentType, out var type) ? type : null;");
        sb.AppendLine();

        // GetCodename method
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string? GetCodename(Type contentType)");
        sb.AppendLine("        => _typeToCodename.TryGetValue(contentType, out var codename) ? codename : null;");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    /// <summary>
    /// Lightweight data carrier for the incremental pipeline.
    /// Implements <see cref="IEquatable{T}"/> excluding <see cref="Location"/>
    /// so the pipeline can skip regeneration when content types haven't changed.
    /// </summary>
    private readonly struct ContentTypeInfo(
        string? codename,
        string fullyQualifiedTypeName,
        string typeName,
        Location location,
        bool isInterface,
        bool isAbstract) : IEquatable<ContentTypeInfo>
    {
        public string? Codename { get; } = codename;
        public string FullyQualifiedTypeName { get; } = fullyQualifiedTypeName;
        public string TypeName { get; } = typeName;
        public Location Location { get; } = location;
        public bool IsInterface { get; } = isInterface;
        public bool IsAbstract { get; } = isAbstract;

        public bool Equals(ContentTypeInfo other) =>
            Codename == other.Codename &&
            FullyQualifiedTypeName == other.FullyQualifiedTypeName &&
            TypeName == other.TypeName &&
            IsInterface == other.IsInterface &&
            IsAbstract == other.IsAbstract;

        public override bool Equals(object? obj) => obj is ContentTypeInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + (Codename?.GetHashCode() ?? 0);
                hash = hash * 31 + (FullyQualifiedTypeName?.GetHashCode() ?? 0);
                return hash;
            }
        }
    }
}
