name: "Dependency track analysis"

on:
  push:
    branches:
      - master
      - vnext
      - vNext
  pull_request:
    branches:
      - master
      - vnext
      - vNext
  schedule:
    - cron: '0 7 * * 1'

jobs:
  Deptrack-build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Install CycloneDX
      run: dotnet tool install --global CycloneDX
    - name: Create SBOM
      run: dotnet CycloneDX ./Kontent.Ai.Delivery.sln -o ./cyclone
    - name: Upload SBOM
      uses: DependencyTrack/gh-upload-sbom@v3
      with:
        serverhostname: ${{ secrets.DEPENDENCYTRACK_SERVER_URL }}
        apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
        projectname: 'Delivery SDK .NET'
        projectversion: ${{ github.head_ref || github.ref_name }}
        bomfilename: "./cyclone/bom.xml"
        autocreate: true
